remote_theme: pages-themes/minimal
title: Brian Drake
author: Brian Drake
hide_author: true
logo: assets/img/Fire dancing.jpg
description: |
  Hello, I'm Drake
  
  I am currently a PhD researcher, looking at causal AI for decision making. 

  I originally put this website together to document my journey from immunoassay scientist to ML engineer. However, the more I've engaged the more I love about the dscipline. And so the website grows!

  And of course thank you for visiting ☕ 
links:
  - title: Researcher Profile
    url: https://researchers.adelaide.edu.au/profile/brian.drake
  - title: LinkedIn
    url: https://www.linkedin.com/in/drackonack
paginate: 6
paginate_path: "/posts/:num"
plugins:
  - jekyll-paginate